### ISSUE TITLE
Find a logo

### ISSUE THREAD

**Issue by triat** [triat/yogi-bot#6]
Generate something with that? https://mybrandnewlogo.com/

**Comment by mirzazulfan** [comment]
Hi. Do you need a logo for your project?

**Comment by triat** [comment]
Hey @mirzazulfan,

I'm not really in a rush (as I'm starting the project) but it would be nice to have something yes :)

**Comment by mirzazulfan** [comment]
I've designed a logo. Maybe you like it. :)
![bot](https://user-images.githubusercontent.com/36124339/55718987-43d88b00-5a27-11e9-92ba-65c5be37010b.png)

**Comment by triat** [comment]
Hey,

thanks a lot @mirzazulfan! It was really quick! 

I'll take it for now, I had nothing in mind so it will do the job and maybe we will change it when we have a more precise idea of what we want :) 

Again thanks for your work 👍

**Comment by mirzazulfan** [comment]
Hi @triat Good to know. I created a pr, if you need help in the future, dont hesitate to contact me. Im happy to help open source project. Best Regard.

**Comment by triat** [comment]
Awesome thanks a lot, I'll keep your name in case I need help again :)
